# Generated by Django 6.0 on 2025-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('required_skills', models.TextField()),
                ('min_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('experience', models.IntegerField(help_text='Experience in years')),
                ('uploaded_file', models.FileField(upload_to='resumes/')),
                ('screening_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
